on: [push, pull_request]
name: test and analyze
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  main:
    strategy:
      matrix:
        go-version: [1.14, 1.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: install go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout code
      uses: actions/checkout@v2
    - name: test
      run: go test -cover ./...
    - name: install analyzers
      if: matrix.go-version >= '1.16'
      run: |
        go install github.com/nishanths/exhaustive/cmd/exhaustive@latest
        go install github.com/gordonklaus/ineffassign@latest
        go install github.com/kisielk/errcheck@latest
    - name: analyze
      if: matrix.go-version >= '1.16'
      run: |
        go vet ./...
        exhaustive -checking-strategy name ./...
        ineffassign ./...
        errcheck ./...
